src/objects/Influence__c.object
<CustomObject>
    <fields>
        <fullName>ACD_Rank__c</fullName>
        <label>ACD Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>AIP_Rank__c</fullName>
        <label>AIP Rank</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Avg_Interactions_Post__c</fullName>
        <formula>if(  Posts_Created__c &gt; 0, ( Comments_Received__c +  Likes_Received__c ) /  Posts_Created__c, 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avg. Interactions/Post</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CC_Rank__c</fullName>
        <label>CC Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>CR_Rank__c</fullName>
        <label>CR Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ChatterRank__c</fullName>
        <formula>MAX( 100 - ( FLOOR(( Ranking__c * 100 ) / Influence_Parent__r.Total_Records__c )), 1 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>ChatterRank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Comments Created</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments_Per_Day__c</fullName>
        <formula>if( Days_with_Comments__c &gt; 0, ( Comments_Received__c +  Likes_Received__c ) /  Days_with_Comments__c, 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avg. Interactions/Day</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Comments Received</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Days_with_Comments__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Days with Comments</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>F_Rank__c</fullName>
        <label>F Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Followers__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Followers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Influence_Formula__c</fullName>
        <formula>( ( 40 * ( Influence_Parent__r.Total_Records__c -  AIP_Rank__c ) ) + ( 25 * ( Influence_Parent__r.Total_Records__c -  PR_Rank__c ) ) + ( 20 * ( Influence_Parent__r.Total_Records__c -  ACD_Rank__c ) ) + ( 10 * ( Influence_Parent__r.Total_Records__c -  F_Rank__c ) ) + ( 5 * ( Influence_Parent__r.Total_Records__c -  CC_Rank__c ) ) / 100 ) / Influence_Parent__r.Total_Records__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Influence Formula</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Influence_Parent__c</fullName>
        <label>Influence Parent</label>
        <referenceTo>Influence_Parent__c</referenceTo>
        <relationshipName>Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Likes_Received_Rank__c</fullName>
        <label>Likes Received Rank</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Likes_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Likes Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PC_Rank__c</fullName>
        <label>PC Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PR_Rank__c</fullName>
        <label>PR Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posts_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Posts Created</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posts_Received__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Posts Received</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Influence</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Influence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Influences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Influence_Parent__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when you&apos;re ready to distribute the results of this snapshot to your users on the My Influence tab.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Avg_Day_Comments_Sum__c</fullName>
        <label>Avg. Day Interaction Sum</label>
        <summarizedField>Influence__c.Comments_Per_Day__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Avg_Interactions_Post__c</fullName>
        <formula>if(  Posts_Created_Sum__c &gt; 0, ( Comments_Received_Sum__c +  Likes_Received_Sum__c ) /  Posts_Created_Sum__c , 0 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Avg. Interactions/Post</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments_Created_Sum__c</fullName>
        <label>Comments Created Sum</label>
        <summarizedField>Influence__c.Comments_Created__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Comments_Received_Sum__c</fullName>
        <label>Comments Received Sum</label>
        <summarizedField>Influence__c.Comments_Received__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <inlineHelpText>Ending boundary of Chatter data to be used in this calculation.</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Followers_Sum__c</fullName>
        <label>Followers Sum</label>
        <summarizedField>Influence__c.Followers__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Influence_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Influence Sum</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Likes_Received_Sum__c</fullName>
        <label>Likes Received Sum</label>
        <summarizedField>Influence__c.Likes_Received__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Median_Comments_Created__c</fullName>
        <label>Median Comments Created</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Comments_Received__c</fullName>
        <label>Median Comments Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Day_Comments__c</fullName>
        <label>Median Day Interactions</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Followers__c</fullName>
        <label>Median Followers</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Influence__c</fullName>
        <label>Median Influence</label>
        <precision>13</precision>
        <scale>3</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Interactions_Post__c</fullName>
        <label>Median Interactions/Post</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Likes_Received__c</fullName>
        <label>Median Likes Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Posts_Created__c</fullName>
        <label>Median Posts Created</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Posts_Received__c</fullName>
        <label>Median Posts Received</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Posts_Created_Sum__c</fullName>
        <label>Posts Created Sum</label>
        <summarizedField>Influence__c.Posts_Created__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Posts_Received_Sum__c</fullName>
        <label>Posts Received Sum</label>
        <summarizedField>Influence__c.Posts_Received__c</summarizedField>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now() - 180</defaultValue>
        <inlineHelpText>Beginning boundary of Chatter data to be used in this calculation.</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <label>Total Influence Records</label>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Influence Snapshot</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Influence Parent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influence Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/influenceTable.cls
// Jonathan Hersh - jhersh@salesforce.com - Dec '10

public with sharing class influenceTable {
    public ID userID         { get; set; }
    public ID ipID              { get; set; }
    public influence_parent__c ip    { get; set; }
    public User u            { get; set; }
    public integer deptRank     { get; set; }
    public integer deptSize     { get; set; }
    public integer globalSize   { get; set; }
    
    public influenceTable() {}
    
    public infLine[] getMetrics() {
        infLine[] infs = new infLine[] {};
        
        try {
            u = [select id, name, email, department, firstname
            from User
            where id = :userID];
        } catch( Exception e ) {
            return null;
        }
        
        try {
            ip = [select id, total_records__c, posts_created_sum__c,
            median_posts_created__c, posts_received_sum__c, median_posts_received__c,
            comments_created_sum__c, median_comments_created__c, comments_received_sum__c,
            median_comments_received__c, median_day_comments__c,
            avg_day_comments_sum__c, influence_sum__c,
            median_influence__c, followers_sum__c, median_followers__c, median_likes_received__c,
            likes_received_sum__c, avg_interactions_post__c, median_interactions_post__c
            from Influence_Parent__c
            where id = :ipID];
        } catch( Exception e ) {
            return null;
        }
            
        Influence__c myInf;
        
        try {
            myInf = [select id, pc_rank__c, pr_rank__c, cc_rank__c, cr_rank__c,
            acd_rank__c, influence_formula__c, 
            comments_per_day__c, posts_created__c, posts_received__c, comments_created__c,
            comments_received__c, followers__c, days_with_comments__c, influence_parent__c,
            ranking__c, f_rank__c, likes_received__c, likes_received_rank__c, avg_interactions_post__c,
            aip_rank__c, chatterrank__c
            from Influence__c
            where influence_parent__c = :ip.id
            and user__c = :u.id
            order by ranking__c asc limit 1];
        } catch( Exception e ) {
            return null;
        }
        
        // Get the influence scores for everyone else in our department
        Influence__c[] deptInfs = [select id, pc_rank__c, pr_rank__c, cc_rank__c, cr_rank__c,
            acd_rank__c, influence_formula__c, 
            comments_per_day__c, posts_created__c, posts_received__c, comments_created__c,
            comments_received__c, followers__c, days_with_comments__c, ranking__c, f_rank__c,
            likes_received__c, likes_received_rank__c, avg_interactions_post__c, aip_rank__c,
            chatterrank__c
            from Influence__c
            where influence_parent__c = :ip.id
            and user__r.department = :u.department
            and user__r.isactive = true
            and user__r.usertype = 'Standard'
            order by ranking__c asc limit 950];
            
        Double[] scores;
        Integer counter;
        
        // First, rank against our dept's PC score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.pc_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.pc_rank__c )
                break;
        }
        
        infLine il = new infLine();
        il.metric = 'Posts Created<sup>1</sup>';
        il.avgNum = ip.posts_created_sum__c / ip.total_records__c;
        il.medNum = ip.median_posts_created__c;
        il.myVal = myInf.posts_created__c;
        il.myRank = myInf.pc_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il ); 
        
        // PR score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.pr_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.pr_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Posts Received<sup>2</sup>';
        il.avgNum = ip.posts_received_sum__c / ip.total_records__c;
        il.medNum = ip.median_posts_received__c;
        il.myVal = myInf.posts_received__c;
        il.myRank = myInf.pr_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il );      
        
        // CC score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.cc_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.cc_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Comments Created';
        il.avgNum = ip.comments_created_sum__c / ip.total_records__c;
        il.medNum = ip.median_comments_created__c;
        il.myVal = myInf.comments_created__c;
        il.myRank = myInf.cc_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il );     
        
        // CR score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.cr_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.cr_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Comments Received<sup>3</sup>';
        il.avgNum = ip.comments_received_sum__c / ip.total_records__c;
        il.medNum = ip.median_comments_received__c;
        il.myVal = myInf.comments_received__c;
        il.myRank = myInf.cr_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il ); 
        
        // Likes Received score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.likes_received_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.likes_received_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Likes Received';
        il.avgNum = ip.likes_received_sum__c / ip.total_records__c;
        il.medNum = ip.median_likes_received__c;
        il.myVal = myInf.likes_received__c;
        il.myRank = myInf.likes_received_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il ); 
        
        // F score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.f_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.f_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'New Followers';
        il.avgNum = ip.followers_sum__c / ip.total_records__c;
        il.medNum = ip.median_followers__c;
        il.myVal = myInf.followers__c;
        il.myRank = myInf.f_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il );  
        
        // AIP score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.aip_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.aip_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Avg. Interactions Received/Post';
        il.avgNum = ip.avg_interactions_post__c;
        il.medNum = ip.median_interactions_post__c;
        il.myVal = myInf.avg_interactions_post__c;
        il.myRank = myInf.aip_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = false;
        
        infs.add( il );  
        
        // ACD score
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.acd_rank__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.acd_rank__c )
                break;
        }
        
        il = new infLine();
        il.metric = 'Avg. Interactions Received/Day<sup>4</sup>';
        il.avgNum = ip.avg_day_comments_sum__c / ip.total_records__c;
        il.medNum = ip.median_day_comments__c;
        il.myVal = myInf.comments_per_day__c;
        il.myRank = myInf.acd_rank__c.intvalue();
        il.deptRank = counter;
        il.isInteger = false;
        
        infs.add( il ); 
        
        // ChatterRank
        scores = new Double[] {};
        counter = 0;
        
        for( Influence__c inf : deptInfs )
            scores.add( inf.ranking__c );
            
        scores.sort();
            
        for( Double i : scores ) {
            counter++;
            if( i == myInf.ranking__c )
                break;
        }
        
        il = new infLine();
        il.metric = '<strong>ChatterRank</strong><sup>5</sup>';
        il.avgNum = null; //ip.influence_sum__c / ip.total_records__c;
        il.medNum = null; // ip.median_influence__c;
        il.myVal = myInf.chatterrank__c;
        il.myRank = myInf.ranking__c.intvalue();
        il.deptRank = counter;
        il.isInteger = true;
        
        infs.add( il ); 
        
        deptRank = counter;
        deptSize = deptInfs.size();
        globalSize = ip.total_records__c.intvalue();
            
        return infs;
    }   

    public class infLine {
        public string metric    { get; set; }
        public double avgNum    { get; set; }
        public double medNum    { get; set; }
        public double myVal     { get; set; }
        public integer myRank   { get; set; }
        public integer deptRank { get; set; }
        public boolean isInteger  { get; set; }
    }
    
    public static testmethod void runTest() {
        // New Inf parent
        Influence_Parent__c ip = new Influence_Parent__c( active__c = true, start_time__c = datetime.now().addMonths(-12), end_time__c = datetime.now() );
        insert ip;
        
        // New inf
        Influence__c inf = new Influence__c( influence_parent__c = ip.id, user__c = userinfo.getuserid(), pc_rank__c = 1, cc_rank__c = 1,
            pr_rank__c = 1, cr_rank__c = 1, f_rank__c = 1, ranking__c = 1, aip_rank__c = 1, acd_rank__c = 1, likes_received_rank__c = 1 );
        insert inf;
        
        influenceTable it = new influenceTable();
        it.userid = userinfo.getuserid();
        it.ipID = ip.id;
        
        infLine[] infs = new infLine[] {};
        
        infs = it.getMetrics();
        
        system.assertEquals( 9, infs.size() );
    }
}