src/objects/Influence__c.object
<CustomObject>
    <fields>
        <fullName>CC_Rank__c</fullName>
        <label>CC Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Comments_Created__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Comments Created</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Influence_Parent__c</fullName>
        <label>Influence Parent</label>
        <referenceTo>Influence_Parent__c</referenceTo>
        <relationshipName>Influence</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Ranking__c</fullName>
        <label>Ranking</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Influence</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>User Influence</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Influence Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Influences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Influence_Parent__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Check this box when you&apos;re ready to distribute the results of this snapshot to your users on the My Influence tab.</inlineHelpText>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>End_Time__c</fullName>
        <defaultValue>now()</defaultValue>
        <inlineHelpText>Ending boundary of Chatter data to be used in this calculation.</inlineHelpText>
        <label>End Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Influence_Sum__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Influence Sum</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Jobs_Executed__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Jobs Executed</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Maximum_Concurrent_Batches__c</fullName>
        <defaultValue>5</defaultValue>
        <inlineHelpText>The maximum number of simultaneous Apex Batch jobs to launch during this calculation. If you&apos;re not sure what this is, leave it at 5.</inlineHelpText>
        <label>Maximum Concurrent Batches</label>
        <precision>2</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Median_Comments_Created__c</fullName>
        <label>Median Comments Created</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Start_Time__c</fullName>
        <defaultValue>now() - 180</defaultValue>
        <inlineHelpText>Beginning boundary of Chatter data to be used in this calculation.</inlineHelpText>
        <label>Start Time</label>
        <required>true</required>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Ready</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Loading Chatter Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sorting Data</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Finalizing Influence</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Records__c</fullName>
        <label>Total Influence Records</label>
        <summaryForeignKey>Influence__c.Influence_Parent__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Influence Snapshot</label>
    <nameField>
        <displayFormat>IP-{0000}</displayFormat>
        <label>Influence Parent Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Influence Snapshots</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/orderingBatch.cls
// Jonathan Hersh - jhersh@salesforce.com - 12/2010
// Ordering batch calculator

global class orderingBatch implements Database.Batchable<sObject>, Database.Stateful {

    global String ipID;
    global Influence_Parent__c ip   { get; set; }
    global integer pos { get; set; }
    global integer curTotal { get; set; }
    global decimal totalInf { get; set; }
    global decimal median   { get; set; }
    global string sortField;
    global string rankField;
    global string medianField;
    global boolean doUpdateParent;

    global Database.QueryLocator start(Database.BatchableContext BC){        
        pos = 1;
        curTotal = 0;
        totalInf = 0.0;
        median = 0.0;
        
        try {
            ip = [select id, jobs_executed__c, total_records__c, status__c from Influence_Parent__c where id = :ipID];
        } catch( Exception e ) {
            return null;
        }
        
        return Database.getQueryLocator('select id, '+ rankField +', '+ sortField +' '+
            ' from Influence__c '+
            ' where influence_parent__c = :ipID '+
            ' order by '+ sortField +' desc');
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope){
        // Try to recover if something really wrong happens
        try {
            ip = [select id, jobs_executed__c, total_records__c, status__c from Influence_Parent__c where id = :ipID];
        } catch( Exception e ) {
            return;
        }
        
        for( integer j = 0; j < scope.size(); j++ ) { 
            integer i = j > 0 ? j - 1 : j;  
            decimal prev, cur;
            
            curTotal++;
            
            if( scope[i].get( sortField ) == null )
                prev = 0;
            else {
                try {
                    prev = decimal.valueof( double.valueof( scope[i].get( sortField ) ) );
                } catch( TypeException te ) {
                    prev = decimal.valueof( string.valueof( scope[i].get( sortField ) ) );
                }
            }
            
            if( scope[j].get( sortField ) == null )
                cur = 0;
            else {
                try {
                    cur = decimal.valueof( double.valueof( scope[j].get( sortField ) ) );
                } catch( TypeException te ) {
                    cur = decimal.valueof( string.valueof( scope[j].get( sortField ) ) );
                }
            }
                        
            if( cur < prev )
                pos = curTotal;
                
            // If we're sorting influence, add it to our total
            if( rankField.contains('ranking__c') )
                totalInf += cur;
                
            // Are we at the median?
            if( ip.total_records__c > 2 && curTotal == Math.ceil( ip.total_records__c / 2 ) )
                median = cur;
                            
            scope[j].put( rankField, pos );
        }
        
        update scope;
    }

    global void finish(Database.BatchableContext BC) {                  
        try {
            ip = Database.query('select id, influence_sum__c, status__c, '+ medianField +' from Influence_Parent__c where id = :ipID');
        } catch( Exception e ) {
            return;
        }
        
        try {
            ip.put( medianField, median );
        } catch( Exception e ) {}
            
        if( doUpdateParent )
        {
            if( ip.status__c == 'Sorting Data' )
                ip.status__c = 'Finalizing Influence';
            else if( ip.status__c == 'Finalizing Influence' )
                ip.status__c = 'Complete';
        }
            
        if( totalInf > 0 )
            ip.influence_sum__c = totalInf;
        
        try {
            update ip;   
        } catch( Exception e ) {} 
    }
    
    global static testmethod void testOrdering() {      
        // New Inf parent
        Influence_Parent__c ip = new Influence_Parent__c( active__c = true, start_time__c = datetime.now().addMonths(-6), end_time__c = datetime.now(), status__c = 'Sorting Data',  maximum_concurrent_batches__c = 5 );
        insert ip;
        
        // New inf
        Influence__c inf = new Influence__c( influence_parent__c = ip.id, user__c = userinfo.getuserid(), comments_created__c = 1, cc_rank__c = 0 );
        insert inf;
        
        // New user for us to follow
        Profile p = [select id from Profile where usertype='Standard' limit 1];
        User u = new User(alias = 'standt', email='standarduser@kwutang.demo', 
                        emailencodingkey='UTF-8', lastname='Testing1', firstname='Testing', languagelocalekey='en_US', 
                        localesidkey='en_US', profileid = p.Id, 
                        timezonesidkey='America/Los_Angeles', username='standarduser@kwutang.demo');        
        
        try {
            insert u;
            insert new Influence__c( influence_parent__c = ip.id, user__c = u.id, comments_created__c = 2, cc_rank__c = 0 );
        } catch( Exception e ) {
            return;
        }
        
        orderingBatch ob = new orderingBatch();
        ob.ipID = ip.id;
        ob.doUpdateParent = true;
        ob.sortField = 'comments_created__c';
        ob.rankField = 'cc_rank__c';
        ob.medianField = 'median_comments_created__c';

        Test.StartTest();
        ID batchprocessid = Database.executeBatch(ob);
        Test.StopTest();
    
        //System.assertEquals( 2, [select cc_rank__c from Influence__c where influence_parent__c = :ip.id and user__c = :userinfo.getuserid()].cc_rank__c ); 
    }
}